### ISSUE TITLE
geolite.maxmind.com - no such host

### ISSUE THREAD

**Issue by brouillette** [jpillora/ipfilter#11]
I'm getting this error upon startup;

After running ipfilter.New(...)

"""
Get http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.mmdb.gz: dial tcp: lookup geolite.maxmind.com on 127.0.0.11:53: no such host
"""

The site is down - what should be done instead? 
Wait for it to come back up, or use a different library?

Thanks..

**Comment by crazy-max** [comment]
A [MaxMind's license key is required](https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/) in order to download GeoLite2 databases.

@jpillora I have created a service to download GeoIP databases called [geoip-updater](https://github.com/crazy-max/geoip-updater) and I think we could use the [MaxMind client](https://github.com/crazy-max/geoip-updater/tree/master/pkg/maxmind) here. What do you think?

**Comment by pierreN** [comment]
Hmm the web archive server doesn't answer now. Too bad. Your ipfilter package was quite nice and easy to use, but this breaks it. It would be nice to have an option to disable GeoIP filtering completely in the meanwhile (so that we don't need the DB).

**Comment by crazy-max** [comment]
@pierreN You can use [this link](https://github.com/crazy-max/echo-ipfilter/blob/master/ipfilter.go#L55) in the meantime.

**Comment by pierreN** [comment]
This archive link doesn't answer here ? Anyway I ended up subscribing to maxmind and using their `mmdb` file, thanks!

**Comment by brouillette** [comment]
The archive link worked for me, but I don't know how long it will hold up before the archive is overwritten. Until then, this will do! 
Thanks
